# Generated by Django 4.2.11 on 2024-04-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('school', 'level', 'term', 'academic_year')},
        ),
    ]
