# Generated by Django 4.2.11 on 2024-04-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_fee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('student', 'school', 'subject', 'level', 'week')},
        ),
    ]
