# Generated by Django 4.2.11 on 2024-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_payslip_total_allowances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
