# Generated by Django 4.2.11 on 2024-04-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_notification_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receipient',
            new_name='recipient',
        ),
    ]
