# Generated by Django 4.2.11 on 2024-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_user_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
