# Generated by Django 4.2.11 on 2024-04-30 15:57

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_user_reset_password_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='coreapp.curriculum'),
        ),
    ]
