# Generated by Django 4.2.11 on 2024-04-30 16:01

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_curriculum_student_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.CharField, to='coreapp.curriculum'),
            preserve_default=False,
        ),
    ]
