# Generated by Django 4.2.11 on 2024-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_alter_student_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
