# Generated by Django 4.2.11 on 2024-05-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_transactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.transactionitem'),
            preserve_default=False,
        ),
    ]
