# Generated by Django 4.2.11 on 2024-05-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_bill_studentbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coreapp.school'),
            preserve_default=False,
        ),
    ]
