# Generated by Django 4.2.11 on 2024-05-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_bill_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Academic_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='coreapp.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='term',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='coreapp.term'),
            preserve_default=False,
        ),
    ]
