# Generated by Django 4.2.11 on 2024-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
