# Generated by Django 4.2.11 on 2024-05-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_studentbill_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbill',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='total_paid',
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.bill')),
                ('student_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.studentbill')),
            ],
        ),
    ]
