# Generated by Django 4.2.11 on 2024-05-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_remove_studentbill_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='bill',
        ),
    ]
