# Generated by Django 4.2.11 on 2024-05-12 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_remove_billpayment_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 12, 6, 37, 7, 260094, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
