# Generated by Django 4.2.11 on 2024-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0025_studentbill_comment_alter_billpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='constituency',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='kenya', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='ward',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
