# Generated by Django 4.2.11 on 2024-05-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0026_student_constituency_student_county_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
    ]
