# Generated by Django 4.2.11 on 2024-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0027_remove_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
