# Generated by Django 4.2.11 on 2024-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0030_user_constituency_user_county_user_gender_user_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=30)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=30)),
                ('user_phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
