# Generated by Django 4.2.11 on 2024-05-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0031_mpesapayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='category_level',
        ),
        migrations.AddField(
            model_name='school',
            name='constituency',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='county',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='curriculum',
            field=models.CharField(default='CBC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='head_teacher',
            field=models.CharField(default='defaulthead@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='population',
            field=models.CharField(default='0-50', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_email',
            field=models.EmailField(default='defaultschoolemail@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='ward',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
