# Generated by Django 4.2.11 on 2024-05-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0032_remove_school_category_level_school_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='note',
            field=models.TextField(default='no note'),
            preserve_default=False,
        ),
    ]
