# Generated by Django 4.2.11 on 2024-05-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0033_school_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
