# Generated by Django 4.2.11 on 2024-05-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0034_alter_school_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='curriculum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='population',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
