# Generated by Django 4.2.11 on 2024-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0036_student_academic_year_student_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='term',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
