# Generated by Django 4.2.11 on 2024-05-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0037_academicyear_current_term_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feebalance',
            name='level',
        ),
    ]
